### ISSUE TITLE
Is this hosted?

### ISSUE THREAD

**Issue by allanchau** [behaviorbot/update-docs#13]
I installed the app, but the bot doesn't seem to be running.
Do I need to create my own app and deploy it?

**Comment by hiimbex** [comment]
Hi @allanchau! It looks to be working to me! See: https://github.com/behaviorbot/update-docs/pull/14

Did you add your comment content's to a `.github/config.yml` file like so:
https://github.com/behaviorbot/update-docs/blob/828f8cfa99a7f17a70287fe76a1941c5e23592bd/.github/config.yml#L6-L7

If you don't specify comment contents, the bot won't run.

**Comment by allanchau** [comment]
Strange, that is definitely there and merged into master.
I made a new PR with changes to the `.github` folder only, perhaps that is why it didn't run?

**Comment by hiimbex** [comment]
Do you have a link to the pr?

**Comment by allanchau** [comment]
Sorry, it is a private repo.
This is the `config.yml` if that helps
```markdown
updateDocsComment: >
  Oops, did you forget to update the documentation?
updateDocsTargetFiles:
  - CHANGELOG
  - README
  - docs/

```

**Comment by hiimbex** [comment]
Welp, that's my bad! I just sent out a permissions update so the app will work for private repos. It should work after you accept that :)

**Comment by allanchau** [comment]
@hiimbex Seems it still isn't working for me 😢.
I also tried it on a public repo https://github.com/idearium/idearium-lib/pull/64/files
Does it need to be on master before it will start working?

**Comment by hiimbex** [comment]
Yea it needs to be on master.
