### ISSUE TITLE
Swap to standard linting

### ISSUE THREAD

**Issue by hiimbex** [behaviorbot/update-docs#7]
The procedure for doing this is laid out more thoroughly here: https://github.com/behaviorbot/sentiment-bot/issues/13.

Let me know if you have any questions!

**Comment by carloscuesta** [comment]
Hey @hiimbex ! I would be glad to help on this 🖐

**Comment by hiimbex** [comment]
@carloscuesta it's all yours! :)

**Comment by hiimbex** [comment]
Closed via #8
